version: '3.9'

services:
  database:
    image: mysql:8
    command: --max_allowed_packet=419430400 --connect_timeout=60
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product
      MYSQL_USER: product
      MYSQL_PASSWORD: password
    volumes:
      - database_volumes:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1s
      timeout: 20s
      retries: 10
      start_period: 10s
    networks:
      - dev
      
  server:
    build:
      context: .
      dockerfile: apps/docker/backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/product?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: product
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      database:
        condition: service_healthy
        restart: true
    networks:
      - dev
      
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: apps/docker/nginx/Dockerfile
    ports:        
      - "80:80"
    depends_on:
      - database
      - server
    volumes:
    - ./apps/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  database_volumes: